version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.22.0
    - 7.25.0
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.9
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.20.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.0
